import React from 'react';
import { IGeneratedPaper, IAssignment, IQuestion } from '../../types';
import PaperHeader from './PaperHeader';
import SectionBlock from './SectionBlock';

interface PaperDocumentProps {
  paper: IGeneratedPaper;
  assignment: IAssignment;
  onUpdate: (sectionIndex: number, questionIndex: number, updates: Partial<IQuestion>) => void;
  onDelete: (sectionIndex: number, questionIndex: number) => void;
  onAdd: (sectionIndex: number, question: IQuestion) => void;
}

const PaperDocument: React.FC<PaperDocumentProps> = ({
  paper,
  assignment,
  onUpdate,
  onDelete,
  onAdd,
}) => {
  return (
    <div className="bg-white rounded-2xl shadow-xl shadow-black/5 border border-gray-100 overflow-hidden">
      <div className="px-10 pt-10 pb-8">
        <PaperHeader assignment={assignment} />

        <div className="mt-6">
          {paper.sections.map((section, sIdx) => (
            <SectionBlock
              key={sIdx}
              section={section}
              sectionIndex={sIdx}
              onUpdate={onUpdate}
              onDelete={onDelete}
              onAdd={onAdd}
            />
          ))}
        </div>
      </div>

      <div className="border-t border-gray-100 px-10 py-4 bg-gray-50/50 flex items-center justify-between">
        <p className="text-xs text-gray-400">Generated by Veda AI</p>
        <p className="text-xs text-gray-400">
          Total: {paper.sections.reduce((sum, s) => sum + s.questions.reduce((qs, q) => qs + q.marks, 0), 0)} marks ·{' '}
          {paper.sections.reduce((sum, s) => sum + s.questions.length, 0)} questions
        </p>
      </div>
    </div>
  );
};

export default PaperDocument;
